title: 熊本熊本熊's Studio.
subtitle: null
description: null
author: 熊本熊本熊
language: zh-CN
timezone: null
url: 'http://www.kumamon.fun/'
root: /
permalink: ':title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  #enable: false
  line_number: true
  #line_number: false
  auto_detect: true
  #tab_replace: null
  tab_replace: ''
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: butterfly
deploy:
  - type: git
    repository:
      github: 'https://github.com/Gingsguard/Gingsguard.github.io.git'
      coding: 'https://e.coding.net/gingsguard/gingsguard.coding.me.git'
    branch: master
  - type: baidu_url_submitter
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
baidu_url_submit:
  count: 50
  host: 'http://www.kumamon.fun/'
  token: TVyzKx63HHaz5wS0
  path: baidu_urls.txt
jsonContent:
  meta: true
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: true
    excerpt: false
    categories: true
    tags: true
algolia:
  applicationID: VDPPC9ZQ58
  apiKey: dd8522d53ff0e784db664accacac98a8
  indexName: gingsguard
  chunkSize: 5000
neat_enable: true
neat_html:
  enable: false
  exclude:
    - '**/*.ejs'
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
neat_js:
  enable: true
  mangle: true
  output: null
  compress: null
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'
search:
  path: search.xml
  field: post
  content: true